import type { Email } from "@/lib/types"
import { Sparkles } from "lucide-react"

interface EmailSummaryProps {
  email: Email
}

export function EmailSummary({ email }: EmailSummaryProps) {
  // In a real app, this would be generated by an AI service
  const summary = generateSummary(email)

  return (
    <div className="rounded-lg border border-gray-200 bg-gray-100/20 p-4 dark:border-gray-800 dark:bg-gray-800/20">
      <div className="mb-2 flex items-center gap-1 text-sm font-medium text-gray-500 dark:text-gray-400">
        <Sparkles className="h-3.5 w-3.5" />
        AI-Generated Summary
      </div>
      <div className="prose prose-sm max-w-none">
        <p>{summary.mainPoints}</p>

        {summary.keyPoints.length > 0 && (
          <>
            <p className="font-medium mt-3">Key Points:</p>
            <ul>
              {summary.keyPoints.map((point, i) => (
                <li key={i}>{point}</li>
              ))}
            </ul>
          </>
        )}

        {summary.actionItems.length > 0 && (
          <>
            <p className="font-medium mt-3">Action Items:</p>
            <ul>
              {summary.actionItems.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </>
        )}
      </div>
    </div>
  )
}

// Mock function to generate a summary based on email content
function generateSummary(email: Email) {
  // This would be replaced with actual AI processing
  const isWorkEmail =
    email.body.includes("meeting") || email.body.includes("project") || email.body.includes("deadline")
  const isLongEmail = email.body.length > 500

  if (isWorkEmail) {
    return {
      mainPoints: "This email discusses work-related matters including project updates and upcoming meetings.",
      keyPoints: ["Project timeline has been updated", "Meeting scheduled for next week", "Budget approval is pending"],
      actionItems: [
        "Respond with availability for the meeting",
        "Review attached documents before Friday",
        "Prepare status update for your part of the project",
      ],
    }
  } else if (isLongEmail) {
    return {
      mainPoints: "This is a detailed message covering multiple topics and information points.",
      keyPoints: [
        "Several important updates were shared",
        "Background information was provided on recent changes",
        "Future plans were outlined",
      ],
      actionItems: ["Review the detailed information", "Consider the proposed suggestions"],
    }
  } else {
    return {
      mainPoints: "This is a brief message with general information or updates.",
      keyPoints: ["Contains general information", "No urgent matters mentioned"],
      actionItems: [],
    }
  }
}

